# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "HugoTeX"
license = "MIT"
licenselink = "https://github.com/7ma7X/HugoTeX"
description = "LaTeX style hugo theme"
homepage = "http://example.com/"
tags = ["blog", "minimal", "simple", "LaTeX"]
features = ["minimal", "simple", "responsive", "syntax highlight", "LaTeX"]
min_version = "0.59.1"

[author]
  name = "HelloRusk"
  homepage = "https://hellorusk.net"